services:
  fastapi:
    container_name: fastapi
    build: ./api_practice
    ports:
      - "8000:8000"
    env_file:
      - .env
  streamlit:
    container_name: streamlit
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
  gradio:
    container_name: gradio
    build: ./gradio
    ports: 
     - "7860:7860"
    depends_on:
      - fastapi


