# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'predict.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\x12\x07predict\"\x1f\n\x0b\x46ileRequest\x12\x10\n\x08\x63sv_file\x18\x01 \x01(\x0c\"\x1f\n\nStrRequest\x12\x11\n\tjson_data\x18\x01 \x01(\t\"\xd6\x01\n\x03Row\x12\x11\n\tFollowers\x18\x01 \x01(\x05\x12\x11\n\tFollowing\x18\x02 \x01(\x05\x12\r\n\x05Posts\x18\x03 \x01(\x05\x12\x0b\n\x03\x42io\x18\x04 \x01(\x05\x12\x17\n\x0fprofile_picture\x18\x05 \x01(\x05\x12\x15\n\rexternal_link\x18\x06 \x01(\x05\x12\x16\n\x0emutual_friends\x18\x07 \x01(\x05\x12\x0f\n\x07Threads\x18\x08 \x01(\x05\x12\x1b\n\x13\x46ollowing_Followers\x18\t \x01(\x02\x12\x17\n\x0fPosts_Followers\x18\n \x01(\x02\".\n\x10\x44\x61taFrameRequest\x12\x1a\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0c.predict.Row\"+\n\x0fPredictResponse\x12\x18\n\x10predictions_json\x18\x01 \x01(\t2\xd6\x01\n\tPredictor\x12\x41\n\x0fPredictFromFile\x12\x14.predict.FileRequest\x1a\x18.predict.PredictResponse\x12?\n\x0ePredictFromStr\x12\x13.predict.StrRequest\x1a\x18.predict.PredictResponse\x12\x45\n\x0ePredictEachCol\x12\x19.predict.DataFrameRequest\x1a\x18.predict.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=26
  _globals['_FILEREQUEST']._serialized_end=57
  _globals['_STRREQUEST']._serialized_start=59
  _globals['_STRREQUEST']._serialized_end=90
  _globals['_ROW']._serialized_start=93
  _globals['_ROW']._serialized_end=307
  _globals['_DATAFRAMEREQUEST']._serialized_start=309
  _globals['_DATAFRAMEREQUEST']._serialized_end=355
  _globals['_PREDICTRESPONSE']._serialized_start=357
  _globals['_PREDICTRESPONSE']._serialized_end=400
  _globals['_PREDICTOR']._serialized_start=403
  _globals['_PREDICTOR']._serialized_end=617
# @@protoc_insertion_point(module_scope)
